spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/telephony_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: false
    locations: classpath:db/migration

server:
  port: 9090
