spring:
  data:
    mongodb:
      authentication-database: ${MONGODB_AUTH_DATABASE}
      username: ${MONGODB_USERNAME}
      password: ${MONGODB_PASSWORD}
      database: ${MONGODB_DATABASE}
      port: ${MONGODB_PORT}
      host: ${MONGODB_HOST}
